version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: 'Dockerfile'
    container_name: 'api'
    ports:
      - '${HOST_API_PORT}:3000'
    environment:
      DB_DIAL: '${DB_DIAL}'
      DB_HOST: 'db'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASS: '${DB_PASS}'
      JWT_SECRET: '${JWT_SECRET}'
    depends_on:
      - 'db'

  db:
    image: 'mysql:8.0'
    container_name: 'api'
    restart: 'always'
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
